### ISSUE TITLE
Undefined item: path_suffix

### ISSUE THREAD

**Issue by lulloa** [AlvaroSMoreno/apigeex2openapi#1]
const path_suffix = item.Condition._text.split(' ')[item.Condition._text.split(' ').indexOf('MatchesPath')+1].replaceAll('"','').replaceAll(')','').replaceAll('(','');
                                           ^

TypeError: Cannot read properties of undefined (reading '_text')

**Comment by AlvaroSMoreno** [comment]
Solved!
